Repository Signbank/Global-signbank, pull requests merged in 2025-02, with the labels that each got.

#1471 #1434: Removed asgiref from requirements
  requirements.txt
Labels: completed

#1473 #1436: Set DEBUG to False in base.py settings
  signbank/settings/base.py
Labels: completed

#1467 #1408: Repairs to API adding BadRequests responses to endpoints
  signbank/dictionary/views.py
Labels: completed, signbank-dev

#1455 #1447: Search for glosses with annotated sentences in general search
  signbank/dictionary/forms.py
  signbank/query_parameters.py
  signbank/settings/server_specific/default.py
Labels: completed

#1431 #1188: Class for Recent Gloss List View
  signbank/dictionary/adminviews.py
  signbank/dictionary/forms.py
  signbank/dictionary/templates/dictionary/admin_recently_added_glosses.html
  signbank/urls.py
Labels: completed

#1470 1413: Removed Admin buttons where operation is not allowed.
  signbank/dictionary/admin.py
Labels: completed

#1474 Added citation image API endpoint
  signbank/api_interface.py
  signbank/dictionary/urls.py
Labels: API

#1482 #1403: Public view more info
  signbank/dictionary/templates/dictionary/gloss.html
Labels: completed, signbank-dev

#1480 1429 max scroll bar
  signbank/dictionary/adminviews.py
Labels: completed

#1496 #1475: Swagger spec for upload gloss image.
  docs/signbank-api.json
Labels: completed
